from __future__ import annotations

import io
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

from ..config import EXPORT_DIR


def _font_paths() -> tuple[str | None, str | None]:
    candidates = [
        Path(r"C:\Windows\Fonts\arial.ttf"),
        Path(r"C:\Windows\Fonts\ARIAL.TTF"),
        Path(r"C:\Windows\Fonts\segoeui.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        Path("/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"),
    ]
    bold_c = [
        Path(r"C:\Windows\Fonts\arialbd.ttf"),
        Path(r"C:\Windows\Fonts\ARIALBD.TTF"),
        Path(r"C:\Windows\Fonts\segoeuib.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
    ]
    regular = next((str(p) for p in candidates if p.exists()), None)
    bold = next((str(p) for p in bold_c if p.exists()), regular)
    return regular, bold


class ReportPDF(FPDF):
    def header(self):
        self.set_font("Lab", "B", 11)
        self.set_text_color(90, 200, 220)
        self.cell(0, 8, "JOKLOB  |  Mathematics & Physics Research Lab", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(90, 80, 180)
        self.line(10, 16, 200, 16)
        self.ln(4)

    def footer(self):
        self.set_y(-12)
        self.set_font("Lab", size=8)
        self.set_text_color(140, 140, 160)
        self.cell(0, 8, f"page {self.page_no()}  ·  not a peer-reviewed publication", align="C")


def _write_wrapped(pdf: FPDF, text: str, size: int = 11):
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Lab", size=size)
    pdf.set_text_color(20, 20, 28)
    pdf.multi_cell(pdf.epw, 6, text or "-", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)


def _section(pdf: FPDF, title: str):
    pdf.ln(2)
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Lab", "B", 13)
    pdf.set_text_color(40, 40, 90)
    pdf.cell(pdf.epw, 8, title, new_x="LMARGIN", new_y="NEXT")


def build_report(data: dict) -> Path:
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    pdf = ReportPDF()
    regular, bold = _font_paths()
    if not regular:
        raise RuntimeError("No Unicode TTF font found for PDF (need Arial or DejaVu).")
    pdf.add_font("Lab", fname=regular)
    pdf.add_font("Lab", "B", fname=bold or regular)
    try:
        pdf.set_text_shaping(True)
    except Exception:
        pass
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    title = data.get("title") or "Research report"
    lang = data.get("language") or "he"
    pdf.set_font("Lab", "B", 18)
    pdf.set_text_color(15, 20, 60)
    pdf.multi_cell(pdf.epw, 10, title, new_x="LMARGIN", new_y="NEXT")
    _write_wrapped(pdf, datetime.utcnow().strftime("UTC %Y-%m-%d %H:%M"))

    sections = [
        ("1. Research question", data.get("question")),
        ("2. Input data", data.get("input_data")),
        ("3. Variables", data.get("variables")),
        ("4. Assumptions", data.get("assumptions")),
        ("5. Formulas", data.get("formulas")),
        ("6. Step-by-step solution", data.get("steps")),
        ("7. Graphs / illustrations", data.get("graphs_note")),
        ("8. Results", data.get("results")),
        ("9. Verification", data.get("verification")),
        ("10. Limitations and certainty", data.get("limitations")),
        ("11. Sources", data.get("sources")),
        ("12. Version history", data.get("versions")),
    ]
    for heading, body in sections:
        _section(pdf, heading)
        if isinstance(body, list):
            for item in body:
                _write_wrapped(pdf, f"• {item}")
        else:
            _write_wrapped(pdf, str(body) if body else ("אין" if lang == "he" else "None recorded"))

    cert = data.get("certainty_label") or ""
    pdf.ln(3)
    pdf.set_fill_color(230, 235, 255)
    pdf.set_font("Lab", "B", 12)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(pdf.epw, 8, f"Certainty tag: {cert}", fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)
    _write_wrapped(
        pdf,
        "This report was generated by JOKLOB. Unproven claims are labelled. "
        "Do not treat conjectures or simulations as experimental facts.",
        9,
    )

    fname = data.get("filename") or f"joklob_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
    path = EXPORT_DIR / fname
    pdf.output(str(path))
    return path
